name: Publish to Edge Addon Store
on:
    push:
        branches:
            - "release"
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: "v20.11.0"
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Upload
              uses: wdzeng/edge-addon@v2
              with:
                  zip-path: market_packages/target.zip
                  product-id: 2a99ae83-5ec8-4ad2-aa63-9a276fc708ce
                  client-id: ${{ secrets.EDGE_CLIENT_ID }}
                  api-key: ${{ secrets.EDGE_API_KEY}}
                  upload-only: true # not publish
